CREATE TABLE "character"
(
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "current_location_id" BIGINT                                  NOT NULL,
    "experience"          FLOAT8                                  NOT NULL,
    "level"               INTEGER                                 NOT NULL,
    "name"                VARCHAR(255)                            NOT NULL,
    "player_id"           BIGINT,
    CONSTRAINT "character_pkey" PRIMARY KEY ("id")
);
