CREATE TABLE "player"
(
    "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email"    VARCHAR(255),
    "password" VARCHAR(255)                            NOT NULL,
    CONSTRAINT "player_pkey" PRIMARY KEY ("id")
);