CREATE TABLE "character"
(
    "id"                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "current_location_id" BIGINT                                  NOT NULL,
    "experience"          FLOAT8                                  NOT NULL,
    "level"               INTEGER                                 NOT NULL,
    "name"                VARCHAR(255)                            NOT NULL,
    "player_id"           BIGINT,
    CONSTRAINT "character_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "location"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "description" VARCHAR(255)                            NOT NULL,
    "name"        VARCHAR(255)                            NOT NULL,
    CONSTRAINT "location_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "player"
(
    "id"       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email"    VARCHAR(255),
    "password" VARCHAR(255)                            NOT NULL,
    CONSTRAINT "player_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "character"
    ADD CONSTRAINT "fkdfhdn54qtwbhljkvel8h6q8vf" FOREIGN KEY ("player_id") REFERENCES "player" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

