CREATE TABLE "location"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "description" VARCHAR(255)                            NOT NULL,
    "name"        VARCHAR(255)                            NOT NULL,
    CONSTRAINT "location_pkey" PRIMARY KEY ("id")
);
